[project]
name = "gtools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12"
dependencies = [
    "pyblup==1.0.5","gfreader==1.0.5","bioplotkit"
]

# [tool.uv]
# index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
