[project]
name = "gtools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "pyblup @ git+https://gh-proxy.com/https://github.com/MaizeMan-JxFU/pyBLUP",
    "bioplotkit==1.0.2",
    "bed-reader==1.0.6"
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
python-install-mirror = "https://registry.npmmirror.com/-/binary/python-build-standalone/"