[package]
name = "jxglm_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "jxglm_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
numpy = "0.27.1"
rayon = "1.11.0"
libm = "0.2.15"